# Generated by Django 4.0.1 on 2022-03-29 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_comment_owner_alter_notification_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='isRead',
            field=models.BooleanField(default=False),
        ),
    ]
