# Generated by Django 4.0.1 on 2022-03-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileImage',
            field=models.ImageField(blank=True, default='media\\images\\profileImages\\mehdi.png', null=True, upload_to='images/profileImages'),
        ),
    ]
