# Generated by Django 4.0.1 on 2022-04-02 07:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_remove_subscription_subscribeid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verificationToken',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
