# Generated by Django 4.0.1 on 2022-04-02 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_profile_verificationtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='verificationToken',
            field=models.IntegerField(default=353496),
        ),
    ]
